CREATE TABLE IF NOT EXISTS events (
    id SERIAL PRIMARY KEY,
    source_event_id VARCHAR(255),
    source VARCHAR(100) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    category VARCHAR(50),
    severity VARCHAR(20),
    confidence NUMERIC(5, 4),
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    country VARCHAR(100),
    region VARCHAR(100),
    occurred_at TIMESTAMP WITHOUT TIME ZONE,
    detected_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    magnitude NUMERIC(5, 2),
    magnitude_type VARCHAR(20),
    depth_km NUMERIC(8, 2),
    tsunami INTEGER,
    alert VARCHAR(20),
    significance INTEGER,
    event_type VARCHAR(50),
    usgs_url TEXT,
    source_url TEXT,
    image_url TEXT,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    fire_radiative_power NUMERIC(10, 2),
    fire_confidence VARCHAR(20),
    satellite VARCHAR(20),
    instrument VARCHAR(20),
    brightness_temperature_ti4 NUMERIC(8, 2),
    brightness_temperature_ti5 NUMERIC(8, 2),
    daynight VARCHAR(1),
    source_version VARCHAR(50)
);
